
EPISODE_MULTIPLIER = 10
EPISODE_CAP = EPISODE_MULTIPLIER * 1000
EPISODE_SHOW = EPISODE_MULTIPLIER * 100
EPISODE_PRINT = EPISODE_MULTIPLIER * 10
EPISODE_PRINT_TOGGLE = False
EPISODE_RENDER = 50

TIME_STEPS = 200
EPISODE_LEARN = 20

EPSILON = 0.9
EPSILON_CAP = 0.05
EPSILON_DISCOUNT = 0.95
EPSILON_DECAY_RATE = EPSILON_DISCOUNT ** (10 / EPISODE_CAP)

MULTIPLIER_EPSILON = 10
MULTIPLIER_IMPROVE = 0.2
MULTIPLIER_RAND = 0.1

def recalculate():
    global EPISODE_CAP, EPISODE_SHOW, EPISODE_PRINT, EPSILON_DECAY_RATE
    EPISODE_CAP = EPISODE_MULTIPLIER * 1000
    EPISODE_SHOW = EPISODE_MULTIPLIER * 100
    EPISODE_PRINT = EPISODE_MULTIPLIER * 10
    EPSILON_DECAY_RATE = EPSILON_DISCOUNT ** (10 / EPISODE_CAP)